FROM tomcat
MAINTAINER lixiaomin <xiao345@gmail.com>
WORKDIR /usr/local/tomcat/webapps/ROOT
RUN wget https://github.com/zhoujingjie/xiaoyaoji/releases/download/v2.1.5.1/xiaoyaoji-2.1.5.1.zip &&\
    unzip -o xiaoyaoji-2.1.5.1.zip && \
    rm -f xiaoyaoji-2.1.5.1.zip